language: c
sudo: false

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "macos" ]] ; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" = "macos" ]] ; then  brew install xz ; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then cd squashfs-tools/ && make checkstyle ; fi
 - cd squashfs-tools/ && make LZMA_XZ_SUPPORT=1 XZ_SUPPORT=1 XATTR_SUPPORT=

addons:
  apt:
    packages:
      - astyle
      - liblzma5
      - liblzma-dev
